[providers]
node = {}

[variables]
NODE_VERSION = "18"
YARN_VERSION = "1.22.19"
NIXPACKS_NODE_MANAGER = "yarn"

[phases.setup]
aptPkgs = []

[phases.install]
onlyIncludeFiles = ['package.json', 'yarn.lock']
cmd = 'yarn install --frozen-lockfile --production=false'

[phases.build]
cmd = 'yarn build'

[start]
cmd = 'yarn start'